name: 'GitHub Actions WeatherBot'

on:
  schedule: 
    - cron: '0 16 * * * '

jobs: 
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install node'
        uses: actions/setup-node@v1
        uses: actions/checkout@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Run code'
        run: node index.js
        env:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}
